### PR TITLE
fix package name

### PR DESCRIPTION
**Pull request by timfreiheit**
fix similar issue to https://github.com/flutter/flutter/issues/42923
the folder declaration did not match the declared package name

### CODE REVIEW

**Comment by praharshbhatt** [comment]
Can you please update the plugin version?

**Comment by adilwahla** [comment]
you need to update

**Comment by DyaryRaoof** [comment]
having the same issue. not solved by using the latest 1.0.1 update

**Comment by praharshbhatt** [comment]
> having the same issue. not solved by using the latest 1.0.1 update

You'll have to manually rename the folder

**Comment by DyaryRaoof** [comment]
Hi @praharshbhatt so I should change audio_recorder folder to audiorecorder ?

**Pull request closed without merging**
